### ISSUE TITLE
Airplay not working

### ISSUE THREAD

**Issue by rajeevtom** [tomodwyer/airsonos#1]
Hi Tom

I am posting here as well.

Now the next problem, I can see my speaker in airplay list but as soon as I am directing the youtube song to speaker its throwing error on prompt :

rajeevs-air:airsonos root# node ./bin/index.js
Searching for Sonos devices on network...

Bathroom (@ IP, RINCON_9TEMP00:0)

Search complete. Set up 1 device tunnel.
/Users/rajeev/airsonos/bin/tunnel.js:66
metadata: this.generateSonosMetadata(this.deviceName)
^

TypeError: this.generateSonosMetadata is not a function
at icecastServer.start.port (/Users/rajeev/airsonos/bin/tunnel.js:66:24)
at Server. (/Users/rajeev/airsonos/node_modules/nicercast/index.js:103:7)
at Object.onceWrapper (events.js:290:19)
at emitNone (events.js:86:13)
at Server.emit (events.js:185:7)
at emitListeningNT (net.js:1288:10)
at _combinedTickCallback (internal/process/next_tick.js:71:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
rajeevs-air:airsonos root#

Am i doing something wrong ?

Also, I can see my speaker only in youtube window for airplay. Why iPhone Airplay Mirroring is not showing the speaker ? Its showing only my apple TV.

Regards
Rajeev

**Comment by tomodwyer** [comment]
Could you try pulling the latest code with `git pull origin master` and try again? I've just pushed a fix.

**Comment by rajeevtom** [comment]
Hi Tom

I am still getting error as you can see below :

rajeevs-air:airsonos root# git pull origin master
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/tomodwyer/airsonos
 * branch            master     -> FETCH_HEAD
   e03886e..d9ef533  master     -> origin/master
Updating e03886e..d9ef533
Fast-forward
 lib/tunnel.js | 20 +++++++++-----------
 1 file changed, 9 insertions(+), 11 deletions(-)

rajeevs-air:airsonos root# node ./bin/index.js
Searching for Sonos devices on network...

Bathroom (IP, RTEMP)

Search complete. Set up 1 device tunnel.
/Users/rajeev/airsonos/bin/tunnel.js:66
        metadata: this.generateSonosMetadata(this.deviceName)
                       ^

TypeError: this.generateSonosMetadata is not a function
    at icecastServer.start.port (/Users/rajeev/airsonos/bin/tunnel.js:66:24)
    at Server.<anonymous> (/Users/rajeev/airsonos/node_modules/nicercast/index.js:103:7)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1288:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
rajeevs-air:airsonos root# 

Regards
Rajeev

**Comment by tomodwyer** [comment]
Ah sorry my fault. Please could you try deleting the `airsonos/node_modules` folder, run `npm install` then try again?

**Comment by rajeevtom** [comment]
Hi Tom

Its working from you tube 👍  ;-)

Now My second question, why the speaker is not showing up on my iPhone airplay list or Macbook Air list. There I see only Apple TV as an option. Is that normal or do i need to do something else ? 

Regards
Rajeev

**Comment by rajeevtom** [comment]
When I am playing some video in WhatsApp it is going to Speaker(although I did not do anything except electing this speaker in youtube) but when I am playing music in Apple music store on iPhone it is not going to speaker. and speaker is not showing up in airplay mirror list as well.

Am i missing something ?

Regards
Rajeev

**Comment by Pe8er** [comment]
Just tested, it's not crashing anymore. Thank you!!
